name: Build & Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES" > app/google-services.json

      - name: Check Code Formatting
        run: ./gradlew spotlessCheck --stacktrace

      - name: Run Lint
        run: ./gradlew lintDebug --stacktrace

      - name: Run local Tests
        run: ./gradlew testDebug --stacktrace
